#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  Flow:
     security:
        authentication:
           providers:
              DefaultProvider:
                 provider: PersistedUsernamePasswordProvider
                 entryPoint: 'WebRedirect'
                 entryPointOptions:
                    routeValues:
                       '@package': 'Belonet.Ssn'
                       '@controller': 'Login'
                       '@action': 'adminLogin'

  # You might need to uncomment the following lines and specify
  # the location of the PHP binary manually.
#    core:
#      phpBinaryPathAndFilename: 'C:/path/to/php.exe'
